version: '3.7'

services:
  db:
    # Using *-alpine to minimize Docker size, for demo purposes
    image: postgres:12.0-alpine
    environment:
      # Of course, change these for a production deployment
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres_demo
    # This volume should help persist data even when the container is stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
    postgres_data:
